### ISSUE TITLE
Should `forward` be treated as a const lvalue?

### ISSUE THREAD

**Issue by JoelFilho** [hsutter/708#11]
While writing about [708 fixing perfect forwarding issues](https://joelfilho.github.io/blog/2020/forwarding_references/#is-there-any-hope), I came up with the following code:

```c++
void invoke_twice(forward auto f, forward auto... args){
	std::invoke(f, args...);
	std::invoke(f, args...); // Definite last use, automatically forwards
}

int x = 0;
auto increment = [](auto& val){ ++val; };
invoke_twice(increment, x);
```

Should the example above work as an `std::forward` version would?

---

In the current draft, for `forward`, we have:

> x is treated as a const lvalue, except that each definite last use of x preserves the argument’s cv-qualification and value category

With this current wording, the function would not compile, as the lambda parameter expects a non-const lvalue.

> x is treated as an lvalue, preserving its cv-qualifications, except that each definite last use of x also preserves the argument’s value category

Would something like this break any contract or introduce any ambiguity to the current proposal?

**Comment by hsutter** [comment]
Thanks Joel. This is a good example, there are a couple of things going on here.

First, starting with principles, there are two relevant design goals involved:

   - For any parameter passing option we be able to compile the callee body in isolation and know it's correct.
   - A `forward` parameter is forwarded at most once. Forwarding it a second time could end up forwarding a different value if the first forward modified the parameter, which seems like a bug farm and didn't come up in the examples I surveyed.

That said, a potential extension to section 1.3.6 about optional call-site annotation could be to allow `forward` or non-definite-last uses of a `forward` parameter to explicitly forward in cases like the above. I'll add it to the paper. Thanks!

BTW, in this example's parameter `f`, shouldn't at least that one `in f` rather than `forward f`? I'm trying to imagine a situation where an invoke-like function would care whether a Callable (essentially) is itself `const` or not and/or an lvalue or rvalue.

**Comment by JoelFilho** [comment]
> For any parameter passing option we be able to compile the callee body in isolation and know it's correct.

I believe it should be always correct if we only forward in the definite last use. 

I also believe **the only issue is with the "treated as a const lvalue" clause for all other uses**. Forwarding them would yield different results, as you've pointed out. So adding the "explicitly forward in cases like the above" clause might yield the incorrect result with rvalue parameters.

But treating them as the correct lvalue equivalent would not yield different results. For instance, consider this C++20 code:

```c++
void invoke_twice(auto&& f, auto&&... args) {
  std::invoke(f, args...); // We don't forward
  std::invoke(std::forward<decltype(f)>(f), std::forward<decltype(args)>(args)...); // We perfect forward
}

struct append_and_print {
  void operator()(std::string& str) const {
    str += "_X_";
    std::cout << str << '\n';
  }

  void operator()(const std::string& str) const {
    std::cout << str << '\n';
  }
};

void case1() {
  std::string s = "case1";
  invoke_twice(append_and_print{}, s);
}

void case2() {
  invoke_twice(append_and_print{}, "case2");
}
```

[The output](https://godbolt.org/z/sYbYvq) is:

```
case1_X_
case1_X__X_
case2
case2
```

For the rvalue case, the lvalue instance on the first use is const-qualified, while in the non-const lvalue, it stays mutable and appends twice. With the current wording, it would only modify once, at the last use. (Note: my wording is also incorrect, as it would treat the rvalue as a non-const lvalue)

---

On the "compile the callee body in isolation" part, `forward` would only work with templates, correct? 

I believe since `forward` would replace forwarding references, and they only happen with templates, the compiler would still have to compile multiple `forward` function instances for the lvalue and rvalue cases, and different qualifiers.

---

>  I'm trying to imagine a situation where an invoke-like function would care whether a Callable (essentially) is itself const or not and/or an lvalue or rvalue.

If `in` implies immutability, any functor with internal state (i.e. operator() not const-qualified) would fail.

The rvalue qualification is more of an obscure case, but still valid in C++:

```c++
auto concat(std::vector<int> v1, const std::vector<int>& v2){
    v1.insert(v1.end(), v2.begin(), v2.end());
    return v1; // Assuming NRVO
}

struct prefixed_shuffle_printer{
	std::vector<int> prefix;

	// Concatenates a prefix with the input vector, then shuffles it.
	// prefix is copied, then v is appended.
	void operator()(const std::vector<int>& v) & {
		print_shuffled(concat(prefix, v));
	}

	// We can optimize a copy by not copying our prefix.
	void operator()(const std::vector<int>& v) && {
		print_shuffled(concat(std::move(prefix), v));
	}
};
```
