### ISSUE TITLE
inline declaration of out arguments

### ISSUE THREAD

**Issue by shaneasd** [hsutter/708#27]
A feature that was added somewhat recently to C# which eases the pain of using out parameters is the ability to declare them at the point where they're used. i.e. instead of
```
X x = uninitialized;
generateX(out x);
```
to simply have
```
generateX(out X x);
```

This follows the principle of keeping the initialization and declaration of the variable in the same place and makes it less verbose to ignore outputs you don't care about (though if memory serves they later added an even less verbose way to do this).

I certainly don't see this as necessary but it's nice to have so it would be good to consider when deciding on call syntax to make sure the option is kept open.

**Comment by hsutter** [comment]
@shaneasd This overlaps a little with [section 1.3.6 of the paper](https://github.com/hsutter/708/blob/main/708.pdf) about "(optional) Call site explicit side effects." But that's about writing "out" at the call site to be explicit about data flow.

I think it can work in theory, as C# has shown, though note that C++ has more complex initialization than C# so we've often found that things that work in C# with its simpler model don't generalize as well to C++'s needs.

But I worry that it's not a great idea in practice to let programmers to bury a local variable declaration arbitrarily deeply inside an expression, when that variable's lifetime should last beyond the expression to the end of the enclosing scope. That can be totally clear to the compiler, but seems like it could be very confusing to the programmer and lead to subtle code where local variable lifetimes are harder to reason about clearly.

I agree there are potential benefits:

(1) It can save typing the characters `= uninitialized` as you you show at top.

(2) As you say, it would keep initialization and declaration in the same place.

The potential costs:

(1) Buried declarations: I think it's less clear for a local object lifetime to start not at statement scope. Probably the most similar thing to what's suggested above that we have today is the special lifetime extension rule for `const&` local variables. That rule has been perennially confusing and hard to teach (and is now a historical artifact since it has been basically obsoleted by C++17 guaranteed copy elision). But even with that rule, we always visibly declared a new local variable up front at the beginning of a statement so it was easy to see that's what was going on. It seems to me that letting programmers "hide" (my characterizations) such variable declarations arbitrarily deeply inside expressions would be strictly harder to reason about than that,

(2) Multiple declarations: Relatedly, keeping initialization and declaration in the same place means that when there are multiple alternative initializations then we would have multiple declarations of the same variable. Here's a variation of an example I give in the talk, where my proposal allows invoking alternate constructors:

~~~
db_info dbi = uninitialized;
if (main_site_is_available) {
    get_data(main_site,   dbi);
}                      // construct
else {
    get_data(backup_site, dbi, stuff);
}                      // construct
~~~

With the suggestion in this Issue, either we would allow this rewrite that I think illustrates the "buried declaration" visual concern:

~~~
if (main_site_is_available) {
    get_data(main_site,   out db_info dbi);
}                      // construct
else {
    get_data(backup_site, out db_info dbi, stuff);
}                      // construct
~~~

or we don't allow it and require a single declaration and a single initialization, but then we lose the flexibility to express this. I'm not sure which is worse -- that declarations can be buried, or that there is no longer one declaration per variable in the same scope.

With the current proposal, we do have to teach writing `= uninitialized`, but we don't have to teach new places to declare local variables (IMO a new lifetime rule quirk) or multiple declarations of the same variable in the same scope.

**Comment by shaneasd** [comment]
thanks @hsutter . You make a compelling argument.
