### ISSUE TITLE
Is copy elision guaranteed for assignment to uninitialized?

### ISSUE THREAD

**Issue by shaneasd** [hsutter/708#28]
How many copy constructors are run in this code?
``` MyType MakeMyType() { return MyType(123); } ```
```
MyType x = uninitialized;
x = MakeMyType();
```

It seems intuitive that the answer would be that the copy is elided but this text makes me think otherwise:
> Every path containing x’s declaration must contain a definite first use of x before the declaration or initialization of another local variable, and that definite first use must be either to pass x to another function’s out parameter, or else be an assignment-expression to x (which can be from a single-object expression or a possibly-empty initializer_list) **that performs a single constructor call (usually direct-initialization) of x with the right-hand side expression treated as the argument to x’s constructor.**

This seems to make it pretty clear that the copy constructor does get executed though I suppose you could argue that in this case the "single constructor call" is actually ```MyType(123)```.

It would be nice for
```
MyType x = uninitialized;
x = ???;
```
to be, by definition, equivalent to
```
MyType x = ???;
```
which would suggest copy elision should work in this case.

**Comment by hsutter** [comment]
@shaneasd: Good question, I'll add this to the paper to make it clearer. This is what I intended to cover with the key phrase "(usually direct-initialization)"... yes it's intended that for

~~~
MyType x = uninitialized;
x = MakeMyType();
~~~

you get exactly the same behavior in terms of which functions are called as if you had written this in current C++

~~~
MyType x = MakeMyType();
~~~

but just with more expressive flexibility because we can lexically decouple the declaration and initialization.

**Comment by shaneasd** [comment]
Changes clarify a lot. Thanks.
