### ISSUE TITLE
how to handle out parameters that will be discarded 

### ISSUE THREAD

**Issue by ChetSkolos** [hsutter/708#33]
example today:
  void DoCalc(int data, double *x, double *y, double *z)
    {
    if (x) *x=1.1; //some calculation
    if (y) *y=1.1; //some calculation
    if (z) *z=1.1; //some calculation
    }

  void UseDoCalc()
    {
    double x,y,z;

    //need x, y and z,
    DoCalc(1, &x,&y,&z);

    //only need z here
    DoCalc(2, nullptr,nullptr,&z);
    }

example with in/out:
  void DoCalc(in int data, out double x, out double y, out double z)
    {
    //Can I detect if x is to be discarded to avoid part of the calculation?
    x=1.1;
    y=1.1;
    z=1.1;
    }

  void UseDoCalc()
    {
    double x,y,z;

    //need x, y and z,
    DoCalc(1, x,y,z);

    //only need z here, How to call?
    DoCalc(2, nullptr,nullptr,z);
    }

**Comment by hsutter** [comment]
Currently there are no optional `in`, `inout`, `out`, `move`, or `forward` parameters. (Though you can write things like `in optional<double>` and similar.)

In the current proposal, you can still write what you do today because there's nothing wrong with pointer parameters, so you can just write the original code as `in double*` parameters.

If we did allow optional `out` parameters, such as by using pass-by-pointer and allowing `out` on a non-top-level (dereferenced) object:

```
// Not currently proposed: optional arguments
// Strawman syntax: put 'out' in the non-top-level position
void f(double * out x) {
    if (x) *x =1.1;
    // ...
    if (x) use(*x); // would require that *x was first written to
}
```

then this would be still basically the same pattern as the original code with `double*` parameters, but with the additional guarantee that the check must happen and the variable be initialized if the pointer is not null. This would need something like the null checking rules of my Lifetime analysis paper to guarantee that `x` is checked for not-null and `*x` assigned to at least once, and additionally that any later use of `*x` is similarly guarded with the not-null check.

That's a possible future extension, which could apply also to `in`, `inout`, `move`, and `forward` parameters. If we did want to leave the door open for pursuing this non-top-level use of `in` and the rest, it could be a reason not to put those words first before the type, but to put it after the type.
