### ISSUE TITLE
Minor spec quibble to § 1.3.2

### ISSUE THREAD

**Issue by orenelrad** [hsutter/708#36]
Love the proposal, but the following has been nagging me

> An inout parameter is a parameter that the function body can read and write. At least one path must contain a non-const use of x (else the parameter should be in). 

I think this should be relaxed to 

> At least one path must contain a non-const use _except when the function is marked override_

That is, given a virtual function where the caller of the base class that defines is "the callee may modify this", it should be possible to satisfy the interface without necessarily reading it. The parenthetical about how it should be 'in' is true only if the definition doesn't need to satisfy that other constraint.

**Comment by orenelrad** [comment]
Here's a contrived example:

`struct ModifyingIntegerObserver
{
    virtual void valueDidChange(inout int x) = 0;

    // Some day this will automatically happen
    virtual ~ModifyingIntegerObserver() = default;
};

struct PrintObserver : public ModifyingIntegerObserver
{
    virtual void valueDidChange(inout int x) override
    {
        printf("The value is now %d\n", x);
    }
};

struct MakeEvenObserver : public ModifyingIntegerObserver
{
    virtual void valueDidChange(inout int x) final
    {
        x += (x % 2);
    }
};

int main(void)
{
    vector<unique_ptr<ModifyingIntegerObserver>>> observers;
    observers.push_back(make_unique<PrintObserver>());
    observers.push_back(make_unqieu<MakeEventObserver>());
    observers.push_back(make_unique<PrintObserver>());

    int i = 1;
    for(in auto observer : observers) {
        observer.valueDidChange(i);
    }

    return 0;
}`

**Comment by shaneasd** [comment]
I note that this line from the paper suggests the writing should be optional
```auto f( inout X x) { } // present me an X I can read and write``` (page 5)

Page 6 contains a description of inout which appears to agree with yours
```If the function is nonvirtual, at least one path must contain a non-const use of x (otherwise, the parameter should be in)```

I suspect what you're requesting was the intention (or perhaps the result of an earlier edit which missed that definition). Seems like the definition you quote from page 12 should be updated to match the one on page 6 and possibly the comment on page 5 should be corrected.

**Comment by hsutter** [comment]
Exactly, the rule is intended for nonvirtual functions. Page 6 has it right, "If the function is nonvirtual...". I've now added that to 1.3.2 (page 12) as well, and it'll be there next time I push an update. Thanks!

I'll also add a rationale Note like the following in the paper:

A nonvirtual function's implementation is local and static -- it's a single function body, so we can see the entire implementation with only local static analysis, including statically seeing all the uses of a parameter, and can apply a static rule.

A virtual function's implementation is conceptually dynamic -- it's the union of all the function bodies in the base and derived classes, including future ones in derived classes that haven't been written yet (for open, or non-`final`, hierarchies which is the default). That's inherently not visible to local static analysis (for humans or for language rules), including we can't statically see all the uses of a parameter, so we can't apply a static rule.

For virtual functions, `inout` declares the intent that the union of all the bodies of the function needs to be able to both read and write the parameter, but we can’t verify that statically.

**Comment by hsutter** [comment]
Oh, also @shaneasd pointed out that the empty bodies in those sample functions can imply the wrong thing... I've taken a pass at adding `/*...*/` in all those otherwise-empty `{ }` illustrative bodies. Thanks, good catch!

**Comment by shaneasd** [comment]
oh that's actually not what I meant, though I agree. My point was the comment
// present me an X I _can_ read and write
should probably say
// present me an X I _can_ read and _must_ write

**Comment by hsutter** [comment]
Thanks. I can see that if you take just that line by itself, but it's presented (at least initially in 1.1) as a set of five lines that go together, the first two of which are key to this rule:

```
auto f(     in X x) { /*...*/ }	// present me an X I can read from
auto f(  inout X x) { /*...*/ }	// present me an X I can read and write
auto f(    out X x) { /*...*/ }	// present me an X I will assign to
auto f(   move X x) { /*...*/ }	// present me an X I will move from
auto f(forward X x) { /*...*/ }	// present me an X I will pass along
```

So in the context of seeing both of the first two choices as described above...

```
/*1*/ // present me an X I can read from
/*2*/ // present me an X I can read and write
```

... logically if you write 2 but _don't_ actually write (which is the only difference from 1), then there's an inconsistency between the intent you declared for the parameter and what the body actually does with the parameter. An `inout` parameter that never has the `out`-ness used is a misdeclared `in` parameter (it tells the caller the wrong thing), and sometimes is less efficient (e.g., losing pass by value).

But this is a good point, thanks -- I didn't realize the wording could be confusing. I'll keep an eye out though to see if this is confusing to others, and see if I can think of a better phrasing. (If I do change the phrasing, I'd like to find something other than "must write" because I'm afraid that would imply a different wrong thing, namely that the function must write on all paths rather than just on some path... the other three options that already say "will" do mean it in that sense of "on all paths").

That said, one use case I'm watching for is whether people try to declare an `inout` parameter to future-proof their code even if the implementation doesn't currently ever write to it, intending to keep the door open to later making the body actually write to it without an ABI break. If that turns out to be a useful use case, then the you-didn't-write-to-it-on-any-path error maybe should be only a suppressible warning.

**Comment by shaneasd** [comment]
you're right. Technically I guess it should be ```// present me an X I can read and must write on at least one code path``` but that is quite a mouthful.

Personally I find the requirement to write to an inout parameter on at least one path unintuitive. Probably this is because I would do this in c++ currently as T& or in c# as ref T and neither require me to write to the parameter. This doesn't make this the right solution but it does bias my reading. Anything that is ambiguous and could be interpreted as agreeing with my assumptions I will probably unconsciously interpret as such.

Sadly I don't have a suggestion for concisely improving this.

**Comment by shaneasd** [comment]
Incidentally whatever conclusion you reach regarding requiring write on inout, it seems like the same argument would apply to requiring read. ```void x(inout int x){ x = 4; }``` looks equally suspicious as ```void x(inout int x){ std::cout << x; }``` to me. In both cases, the caller has been restricted by the callee and that restriction is not required but comes with expectations from the caller as to what the callee will do.
