### ISSUE TITLE
in parameters obfuscate mutability/mortality of referenced object

### ISSUE THREAD

**Issue by alex-weej** [hsutter/708#4]
```c++
auto do_something(in std::string arg) -> void {
    // arg is "foo"
    some_arbitrary_function_call();
    // arg is "bar"
}
```

If the argument was instead spelled `std::string const& arg` I contend that it's "clearer" that this is merely a readonly reference, and transferring control to any other function could have arbitrary effects on the referenced object. I think the above example is admittedly somewhat contrived, but far more likely to happen with coroutines, e.g.

```c++
auto do_something(in std::string arg) -> std::generator<int> {
    // arg is "foo"
    co_yield(1);
    // arg is "bar"
}
```

Worse is that, for an unfamiliar type, the presence of this behaviour is unpredictable to an author/reviewer because 'cheap to copy' is unpredictable (and may even be changed over time via a trait).

I wrote more about this general issue here in a post a few years ago https://gist.github.com/alex-weej/74d943d7c2d9b881f809cd8183c02de3

---

Edit: As I note in https://github.com/hsutter/708/issues/4#issuecomment-729173282 there is also the possibility that the `in arg` is not merely mutated but actually destroyed. This can easily happen with a caller of a coroutine:

```c++
auto my_coro(in std::string arg) -> task<int> {
    std::cout << "Arg is " << std::quoted(arg);
    co_await(sleep_for(5s));
    std::cout << "Arg is " << std::quoted(arg); // uh oh
}

auto test() -> task<int> {
    return my_coro("Oops you died!"s);
}
```

**Comment by Zastai** [comment]
`in T t` indeed implies only that _you_ can't write to `t`. If `T` is not immutable, it does not guarantee that `t` won't change elsewhere.

Note: you don't even need a lambda to cause this to happen; just call two functions, each on its own thread, passing the same object, once as `inout`, once as `in`.

There will probably be a need to have a flag like `copy` to enforce a copy.
That would then be the way to avoid cases where concurrency might otherwise change the value of the argument during your function. Just like you would perhaps have written `std::string const arg` now.

I'm not sure if it would be useful to have the opposite, an `in` that explicitly never copies (producing the equivalent of `const int&`) for a function that does not modify the value, but does want to observe changes to it. But I suppose `in int&` would already cover that case.

**Comment by klosworks** [comment]
> If the argument was instead spelled std::string const& arg I contend that it's "clearer" that this is merely a readonly reference, and transferring control to any other function could have arbitrary effects on the referenced object.

Agreed, saying `in ` could suggest a copy.

Indeed the current proposal doesn't provide a syntax to force a copy. Of course, you could just omit all modifiers and have a by-value `std::string` argument, but this is indeed makes you consider 6 options for argument passing instead of 5 as claimed in the proposal. So I see it as a teachability problem.

**Comment by klosworks** [comment]
@Zastai 
> That would then be the way to avoid cases where concurrency might otherwise change the value of the argument during your function.

Don't get fooled that you need concurrency for this to be a problem. You don't

**Comment by Zastai** [comment]
> > That would then be the way to avoid cases where concurrency might otherwise change the value of the argument during your function.
> 
> Don't get fooled that you need concurrency for this to be a problem. You don't

True, you could also call code from the function that mutates `arg` (because it has write access to it).
But then at least you have a chance of being aware of this, and behaving accordingly. With concurrency, all bets are off.

**Comment by klosworks** [comment]
> > > That would then be the way to avoid cases where concurrency might otherwise change the value of the argument during your function.
> > 
> > 
> > Don't get fooled that you need concurrency for this to be a problem. You don't
> 
> True, you could also call code from the function that mutates `arg` (because it has write access to it).
> But then at least you have a chance of being aware of this, and behaving accordingly. With concurrency, all bets are off.

Yes although the non-concurrent case would be much more common than the concurrent one. And in the concurrent one you have to plan what to synchronize anyway, which requires a bit more of a high level approach that would also help to prevent such issues. But I agree that in the concurrent case it can be harder to spot the bug in the code.

**Comment by alex-weej** [comment]
I'd like to point out that while both multithreading concurrency and calls to functions (hidden behind co_await/co_yield, or just a function call with no visible definition) can lead to a hypothetical observable problem, it far more commonly leads to a failure to optimize. This is somewhat explicitly acknowledged by writing either:

* `T const&` - save the copy, but assume the worst re aliasing and have to re-read the value several times in the function's code gen
* `T const` - make a copy (or move construct!), and then be able to optimize under the assumption that its value cannot change.

**Comment by alex-weej** [comment]
Finding it interesting that with coroutines, an `in` argument being a `T const&` is actually quite dangerous because it's far more likely that the object will be destroyed (not just mutated!) after the first suspension.

**Comment by alex-weej** [comment]
I've updated the first post with an explanation of this thought.

**Comment by hsutter** [comment]
Thanks! Note this is mentioned in the paper (section 1.3.1, `in` parameters) in this Note:

> There is one design point that we should validate with field experience: If an “in” parameter is aliased by another parameter or global, then although the `in` parameter is treated as `const` in that it cannot be modified directly, its value may change through the alias. This could be a pitfall, which we should determine by getting field usability experience. However, the [P1179R1] Lifetime rules default to banning passing non-owning Pointers that alias, so this may not be a problem in practice.

I've now added a note about coroutines right after that, as follows -- it will be in the next version of 708.pdf I push sometime in the next few days:

> For coroutines, an `in` parameter passed by pointer (much like today a `const&` parameter) can be invalidated/dangling at the first suspension point, particularly if it binds to an rvalue argument. This case is intended to be covered by [P1179R1] Lifetime rules extended for coroutines, where after the first suspension point we would warn about any use of a `const&` or `in` parameter (and potentially other by-pointer passing).

There's a separate issue with coroutines about whether that suspension can happen on function entry so that it would never be safe to refer to even a `const&` parameter today.

Thanks @alex-weej and everyone!
