### ISSUE TITLE
Should out parameters really even exist?

### ISSUE THREAD

**Issue by alex-weej** [hsutter/708#5]
If the goal of this proposal is accidental complexity reduction, perhaps we should be promoting return by value. Are there cases (PMR shambles notwithstanding) where this is not actually possible in modern C++ design? There is a mention of `read_next_chunk` not being return-by-value in the current paper text but I'm not sure I agree with the logic - for such exceedingly rare circumstances (IMO microoptimizations) the explicit use of an `in T*` seems reasonable and appropriate to me.

**Comment by klosworks** [comment]
I don't really see `in T*` as a replacement because it says "in" and *is* "out".

Without analysing a lot of case, I can tell that It would break my flow If I had to either return by value or use inout etc. Imagine I have a function that accepts something as inout. Then I figure out that I'm not reading it anymore. Now, to fix the function signature, I would have to refactor a lot of code inside my function and change the return type to add that extra object. Moveover this means that now I have to return a pair or a tuple. I don't love it.
Add to it the fact that you have to deal with existing types which may not necessarily behave well when you attempt to return them from a function or when you add them to an std::pair.

**Comment by hsutter** [comment]
Yes, return by value is the lion's share of "out" semantics. It embodies "callee-allocated out."

But `out` parameters are essential for two reasons:

   - (minor) They address the remaining 1% of today's "out" semantics that need "caller-allocated out."

   - (major) They allow unified initialization that guarantees initialization with program-meaningful values. Because `out` parameters can take `uninitialized` inputs, they can act as named constructors and enable unifying value setting -- see section 2 of the paper which walks through this, most of which relies on `out`. (Note: this is not implemented yet in the experimental compiler)
