### ISSUE TITLE
Composability of arguments into data structures

### ISSUE THREAD

**Issue by klosworks** [hsutter/708#6]
What if I have 10 arguments to a function and I want to group them into a struct?
I can't do
```
struct A
{
    in int i;
    inout std::vector<char> v;
    out std::string s;
    move std::pair<std::string, bool> p;
    forward std::optional<std::shared_ptr<std::string>> o;
};
```
Likewise, I can't do
```
std::pair<move std::string, std::pair<in int, out float>>
```
or
```
struct B
{
    in int i;
    out std::string s;
};

struct
{
    B b;
    in int x;
};
```
Existing features like `&` `*` and const are composable like this (I think fully in syntax and partially in practice).
I think that the proposal needs to address this issue somehow, even if only to say that this is not a problem. But I suspect that it is a problem in practice.

**Comment by Zastai** [comment]
But fields aren't parameters, and they can stay references and pointers just fine.

If you group "parameters" into a class, the class is the parameter.
In current C++ if you pass a `const A&` you would need to make fields you want to treat as in/out `mutable`, etc. So if you wanted to be able to write to it normally, you would pass it as `A&` and have no way of expressing any existing A contents are ignored.
With this proposal, writing `in A` does the same as `const A&`, and using `inout A` or `out A` you capture the `A&` case while also expressing whether or not you care about the referenced objects contents.

Pointers and references inside A/B work as before, because the proposal is about parameter passing only, NOT about removing pointers/references.

**Comment by klosworks** [comment]
> But fields aren't parameters, and they can stay references and pointers just fine.
> 
> If you group "parameters" into a class, the class is the parameter.

Agreed.

> In current C++ if you pass a `const A&` you would need to make fields you want to treat as in/out `mutable`, etc. So if you wanted to be able to write to it normally, you would pass it as `A&` and have no way of expressing any existing A contents are ignored.

I disagree. I can do something like
```
struct A
{
    const int* p1 = nullptr;
    const int*const p2 = nullptr;
    double* p3 = nullptr;
    std::pair<const int, std::string> stuff;
    const std::vector<int>& vec;
};
```

Here `const` tells a field (or a part of it) should not be modified. Some of this is inconvenient though, for example you can't really initialize `std::pair<const int, std::string> stuff;` and `const std::vector<int>& vec;` outside a constructor of `A`, and that's why I said that the current composability exists fully in syntax and partially in practice.

If I use `A` for just one function or if I can use the same `A` for multiple functions, then I don't even have to annotate individual fields on a per-function basis, and I can just put modifiers in the struct itself. This is the whole point of composability with structs.

I have used such structs in the code to group things. Often fields are just values, which they usually should be, but sometimes it is useful to just have the same modifiers as in the original function arguments.

A more common use case is when I make a local reference
```
const B& b= vec[i];
//do stuff with b
```

This is another case where I have to use something different than the new modifiers to express the same concept.

I guess that the problem I see is that if you have different modifiers for structs and for parameters, then you have
* much more complicated language, more stuff to teach (chipping away at the savings in teaching argument passing)
* you break the flow because you can't just cut and paste from an argument list to a struct or to a template argument.
* you unnecessarily expose yourself to the possibility of unforeseen use cases where you just can't do stuff unless you use *one* of the new or old syntax

> With this proposal, writing `in A` does the same as `const A&`, and using `inout A` or `out A` you capture the `A&` case while also expressing whether or not you care about the referenced objects contents.
> 
> Pointers and references inside A/B work as before, because the proposal is about parameter passing only, NOT about removing pointers/references.

I never said that the proposal is about removing pointers or references. Please, stick to the facts.

On this topic though, I heard Herb say in hist cppcon talk that ideally he wouldn't see a use for references if this passed. I think this was an exaggeration because references are still needed for stuff like the return type of `operator[]`. But this is off topic.

**Comment by hsutter** [comment]
Re the last comment above: Note the paper does address the return type of `operator[]` without using a reference, see section 1.5.2.

Actually yes, I do intend that this proposal be able to subsume and replace all uses of references for parameter/return passing. Of course, this creates a big to-do for me, namely that I need to keep looking for examples that are not yet covered! I don't know of any but there's still work to do and feedback is appreciated.

Other uses of references are problematic or outdated, even though we 'made some have a use' in the language (e.g., lifetime extension). I tried to write down my entire view of this topic back earlier this year in the post ["References, Simply."](https://herbsutter.com/2020/02/23/references-simply/) It touches on several of the cases mentioned in this comment thread:
   - Uses of references as class/struct data members is already problematic and typically discouraged. It has strange effects, some of which I mentioned in the blog post above.
   - Uses of references as local variables, including the lifetime extension special case, is now largely subsumed by C++17's features of guaranteed copy elision and structured bindings.
   - Uses of references for other things, especially for template specialization, are highly suspicious. Yes, that includes `optional<T&>`, described in detail in the blog post... yet, just last week, I saw `optional<T&>` mentioned as a potential solution for something in an email discussion among C++ experts.

I would answer the original point by saying that struct members and parameters aren't the same thing. I do recognize the style of grouping parameters as structs, but I think more often than not this is exposing a weakness -- specifically, why should they be grouped? A key question is: Does the type have any kind of invariant?
   - If yes, that's a clear signal that there is a missing abstraction, and that it should definitely be a type and not list of naked parameters. In the STL the first example that comes to my mind where I might be tempted to use a type to group parameters is for pairs of iterator parameters... but there that's only a symptom, and the underlying problem is that we are missing an abstraction, which is a range (fixed in C++20, thankfully).
   - If no (there is no invariant), then why are we grouping them -- what benefit is it giving over expressing them as a list of parameters?

Thanks for the question and comments. I'll be happy to reopen this if there's something I didn't fully answer or if a new aspect or use case arises -- especially a concrete real-world-like example that motivates using a struct parameter in this way and motivates applying modifiers to the struct members.
