### ISSUE TITLE
How to express always-pass-a-copy?

### ISSUE THREAD

**Issue by Zastai** [hsutter/708#7]
Really enjoyed the talk.

However, is the intent to (eventually) _require_ one of the new `in`/`inout`/`out`/`move`/`forward` parameter flags (otherwise, you'd just move the older way into the "multiple ways of doing things" wedge)?
If so, how do you write `copy_from()` then?
If I understood correctly, all of the 5 flags shown avoid copying. Would you need a 6th flag (like `copy`) to express the intent of copying?

Now, I agree that this might not be a case you want often, but that's all the more reason to make you have to write `copy` to make that intent explicit (as opposed to potentially accidentally copying).

**Comment by alex-weej** [comment]
Also relevant in this discussion: #4

**Comment by hsutter** [comment]
@Zastai Thanks! This is a good question... we might learn we need a `copy` option, this is on my things-to-validate list.

I'll add something like the following to the `in` section of the 708.pdf paper, which will be in there the next time I push it, probably in the next few days:

First, if the function body is going to copy to somewhere else anyway, this is mostly moot since the copy will occur then. I think the real question here is whether a local use of the parameter within the function is guaranteed to have a separate identity from the argument, such as if you care about aliasing (as in #4)..

In the current proposal without `copy`, you can get the nearly identical effect now by passing as `in` and then just copying into a local variable and using that. That "nearly" has three parts:

    - If `in` is going to copy already, this results in two copies. However, both will be trivial/cheap copies, and appear to be regularly optimized away at -O1, as in [this example](https://godbolt.org/z/3shebv).

    - If `in` is going to pass by reference already, this results in exactly one copy. However, it also adds a pointer to the space/time overhead of calling the function, and this appears to be regularly optimized away at -O1 by GCC but not optimized at all by Clang even at -O3, as in [this example](https://godbolt.org/z/r6j3vd).

    - It's an idiom, which doesn't directly express intent. If this turns out to be relatively common, that would be an argument for language support.

As noted this is related to #4.

Thanks again!
