### ISSUE TITLE
Rename `move` to `movein`

### ISSUE THREAD

**Issue by aminya** [hsutter/708#8]
The current proposal uses `move` in the parameter list that means `movein`. However, only using the `move` word can be confusing because `move` can mistakenly be interpreted as `in + move out` (the parameter is passed `in` and it is `moved out`). So, I am proposing to use `movein` instead, which is more descriptive and removes the confusion.

`movein` explicitly shows the intention of writing this code. It is also inline with `in` itself. Whenever someone needs to edit a value inside the function, they can just add `move` behind `in`.

```c++
void myfun(in auto for_reading, movein auto for_editing); 
```

**Comment by klosworks** [comment]
If I understand you correctly, the risk is that the direction of the `move` misunderstood, so that one thinks that the value is moved out of the function rather than into it. I agree, although I don't think this risk is high because there are `out` and `inout` modifiers, so when one learns all 5, they will normally suppose that `move` is *not* out. Also, `std::move` already has the same meaning as `move`, which helps too.

I if it was my decision, it would just be `move`.

**Comment by aminya** [comment]
I think the proper word is `movein`. It explicitly shows the intention of writing this code. It is also inline with `in` itself. Whenever some needs to edit a value inside the function, they can just add `move` behind `in`.

```
void myfun(in for_reading, movein for_editing) 
```

**Comment by klosworks** [comment]
> I think the proper word is `movein`. It explicitly shows the intention of writing this code. It is also inline with `in` itself. Whenever someone needs to edit a value inside the function, they can just add `move` behind `in`.
> 
> ```c++
> void myfun(in auto for_reading, movein auto for_editing); 
> ```

It's better than `movefrom` but I'm still not convinced that it is better than `move`. It's a bit like having `co_yield` instead of `yield`.
Besides, both `movefrom` and `movein` are ambiguous anyway (when considered in isolation). Are you moving `from` the function or `from` the argument? Are you moving `in`-to the function or `in`-to the argument?

**Comment by aminya** [comment]
Well, "in" always means inside the function. We use "out" for what function gives out.

**Comment by hsutter** [comment]
@aminya Thank you for the feedback. Note that the paper currently also has a `move` qualifier on the return value, so the `move` in the parameter list and the `move` on the return value are naturally "in" and "out" respectively. Still, I'll keep this in mind and watch to see if this is confusing as people start trying out the feature -- all naming is subject to change, but I want to change it based on usage experience. Again, thanks!
